apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'jhipster'
  description: 'JHipster Example for Red Hat Developer Hub'
  annotations:
    github.com/project-slug: maximilianopizarro/jhipster-quarkus-test
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: maximilianopizarro5-dev
    backstage.io/kubernetes-id: jhipster
    janus-idp.io/tekton: jhipster
    backstage.io/kubernetes-label-selector: 'app=jhipster'
  links:
    - title: Documentation
      url: https://github.com/maximilianoPizarro/jhipster-quarkus-test/blob/main/README.md
    - url: https://workspaces.openshift.com/#https://github.com/maximilianoPizarro/jhipster-quarkus-test/tree/main?storageType=ephemeral
      title: OpenShift Dev Spaces (VS Code)
      icon: web
  tags:
    - java
    - dev
spec:
  type: service
  lifecycle: experimental
  owner: 'group:default/maximilianopizarro'
